# Generated by Django 5.2.8 on 2026-01-29 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
            ],
        ),
    ]
