# Generated by Django 5.0.6 on 2026-01-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="USER", max_length=10),
        ),
    ]
