# Generated by Django 5.0.6 on 2026-02-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=200, null=True),
        ),
    ]
